### ISSUE TITLE
Production bundle can't run on itch.io

### ISSUE THREAD

**Issue by nilskj** [excaliburjs/template-ts-vite#28]
### Steps to Reproduce
- Use this template
- Install dependecies
- Build production bundle
- Zip it and upload to itch.io

### Expected Result
Game should work, as it does if using the webpack or parcel templates

### Actual Result
Screen stays gray, user gets 403 error (forbidden). See https://nilskjql.itch.io/excalibur-vite-test
![image](https://user-images.githubusercontent.com/495782/149659784-562c72b7-0dc9-4cc1-8b8c-e6e50f3288d1.png)

### Environment
- Browsers and versions: Chrome
- operating system: MacOS
- Excalibur versions: as in template
- When bundling with webpack there is no problem, this seems to be something with the vite bundling and /or how itch.io loads it but i'm not sure where the error is.

### Current Workaround
For a game jam I uploaded the prod bundle to netlify and then it worked, but not optimal in any way.

**Comment by nilskj** [comment]
Nevermind I think this is a problem at itch.io. Vite puts assets in a subfolder and that makes it problematic to run on itch. Webpack puts the whole bundle and files in the same. Read this: https://itch.io/docs/creators/html5#common-pitfalls.

This issue can be closed since this is most likely something with Itch then this template or excalibur :)

**Comment by eonarheim** [comment]
@nilskj this is a good piece of info, I might add this to our documentation. It might be useful to have a section in our documentation around hosting platforms like itch and any of these pitfalls.

@kamranayub @jedeen What are your thoughts?

**Comment by kamranayub** [comment]
Anything that helps when we know there are issues seems good 😊
